// src/react/components/FormField/FormField.tsx
import { cloneElement, isValidElement, useId } from "react";

import { COMPONENT_NAMES, CSS_CLASSES } from "@/core/constants";
import { Tooltip } from "../Tooltip";
import type { TFormFieldProps } from "./FormField.types";

// Components that don't use error prop (they don't display error styles)
const SKIP_ERROR_INJECTION: string[] = [COMPONENT_NAMES.Checkbox, COMPONENT_NAMES.Switch, COMPONENT_NAMES.Radio];

const classes = CSS_CLASSES.formField;

/**
 * FormField component for React
 *
 * A smart layout container that auto-injects id and aria props to form controls
 *
 * @example
 * ```tsx
 * <FormField label="Email" required error={errors.email}>
 *   <Input type="email" value={email} onChange={setEmail} />
 * </FormField>
 *
 * // Horizontal layout with control position
 * <FormField label="Remember me" orientation="horizontal" controlPosition="start">
 *   <Checkbox checked={remember} onChange={setRemember} />
 * </FormField>
 * ```
 */
export function FormField({
  label,
  required = false,
  error,
  tooltip,
  tooltipIcon,
  size = "md",
  orientation = "vertical",
  controlPosition,
  className = "",
  children,
}: TFormFieldProps) {
  const fieldId = useId();
  const errorId = useId();

  const hasError = Boolean(error);

  // Get props from child element
  const childProps = isValidElement(children) ? (children.props as Record<string, unknown>) : {};
  const existingId = childProps.id as string | undefined;

  // Clone child element with auto-injected props
  // Note: only inject error when true to avoid passing false to native elements
  // Skip error injection for Checkbox/Switch/Radio as they don't display error styles
  const childDisplayName = isValidElement(children)
    ? (children.type as { displayName?: string })?.displayName
    : undefined;
  const shouldInjectError = !SKIP_ERROR_INJECTION.includes(childDisplayName as string);

  const childWithProps = isValidElement(children)
    ? // eslint-disable-next-line react-x/no-clone-element -- intentional: inject a11y props
      cloneElement(children, {
        id: existingId || fieldId,
        "aria-describedby": hasError ? errorId : undefined,
        "aria-invalid": hasError || undefined,
        error: shouldInjectError && hasError ? true : undefined,
      } as Record<string, unknown>)
    : children;

  const rootClassNames = [
    classes.root,
    classes.sizes[size],
    classes.orientations[orientation],
    controlPosition ? classes.controlPositions[controlPosition] : "",
    hasError ? classes.states.error : "",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const controlId = existingId || fieldId;

  return (
    <div className={rootClassNames}>
      {label && (
        <div className={classes.labelRow}>
          <label htmlFor={controlId} className={classes.label}>
            {required && <span className={classes.required}>* </span>}
            {label}
          </label>
          {tooltip && tooltipIcon && (
            <Tooltip content={tooltip} placement="top">
              <span className={classes.tooltipTrigger}>{tooltipIcon}</span>
            </Tooltip>
          )}
        </div>
      )}
      <div className={classes.control}>{childWithProps}</div>
      {hasError && (
        <div id={errorId} className={classes.error} role="alert">
          {error}
        </div>
      )}
    </div>
  );
}

FormField.displayName = COMPONENT_NAMES.FormField;

// src/vue/components/FormField/FormField.vue
<script setup lang="ts">
import { computed, provide, readonly, ref, useSlots } from "vue";

import { CSS_CLASSES } from "@/core/constants";
import { Tooltip } from "../Tooltip";
import type { TFormFieldProps } from "./FormField.types";

const classes = CSS_CLASSES.formField;

const props = withDefaults(defineProps<TFormFieldProps>(), {
  required: false,
  size: "md",
  orientation: "vertical",
  className: "",
});

defineSlots<{
  default(): unknown;
  tooltip?(): unknown;
  tooltipIcon?(): unknown;
}>();

// Use useSlots() to detect slot presence at runtime
const slots = useSlots();

// Generate unique IDs
const fieldId = `form-field-${Math.random().toString(36).slice(2, 9)}`;
const errorId = `form-field-error-${Math.random().toString(36).slice(2, 9)}`;

const hasError = computed(() => Boolean(props.error));

// Provide context for child form controls
provide("formFieldId", readonly(ref(fieldId)));
provide(
  "formFieldErrorId",
  computed(() => (hasError.value ? errorId : undefined)),
);
provide("formFieldError", hasError);

const rootClassNames = computed(() => {
  return [
    classes.root,
    classes.sizes[props.size],
    classes.orientations[props.orientation!],
    props.controlPosition ? classes.controlPositions[props.controlPosition] : "",
    hasError.value ? classes.states.error : "",
    props.className,
  ]
    .filter(Boolean)
    .join(" ");
});
</script>

<template>
  <div :class="rootClassNames">
    <div v-if="label" :class="classes.labelRow">
      <label :for="fieldId" :class="classes.label">
        <span v-if="required" :class="classes.required">* </span>
        {{ label }}
      </label>
      <Tooltip v-if="(tooltip || !!slots.tooltip) && !!slots.tooltipIcon" placement="top">
        <span :class="classes.tooltipTrigger">
          <slot name="tooltipIcon" />
        </span>
        <template #content>
          <slot name="tooltip">{{ tooltip }}</slot>
        </template>
      </Tooltip>
    </div>
    <div :class="classes.control">
      <slot />
    </div>
    <div v-if="hasError" :id="errorId" :class="classes.error" role="alert">
      {{ error }}
    </div>
  </div>
</template>
