// src/vue/components/Radio/Radio.vue
<script setup lang="ts">
import { computed } from "vue";

import { CSS_CLASSES } from "@/core/constants";
import type { TRadioProps } from "./Radio.types";

const classes = CSS_CLASSES.radio;

const props = withDefaults(defineProps<TRadioProps>(), {
  size: "md",
  checked: false,
  disabled: false,
  className: "",
});

const emit = defineEmits<{
  "update:modelValue": [value: string | number];
  change: [value: string | number];
}>();

const slots = defineSlots<{
  default?(): unknown;
  checkedIcon?(): unknown;
  uncheckedIcon?(): unknown;
}>();

const isCustomMode = computed(() => Boolean(slots.checkedIcon || slots.uncheckedIcon));

const isChecked = computed(() => {
  if (props.modelValue !== undefined && props.value !== undefined) {
    return props.modelValue === props.value;
  }
  return props.checked;
});

const classNames = computed(() => {
  return [
    classes.root,
    classes.sizes[props.size],
    isCustomMode.value ? classes.custom : "",
    isChecked.value ? classes.states.checked : "",
    props.disabled ? classes.states.disabled : "",
    props.className,
  ]
    .filter(Boolean)
    .join(" ");
});

function handleChange() {
  if (props.value !== undefined) {
    emit("update:modelValue", props.value);
    emit("change", props.value);
  }
}
</script>

<template>
  <label :class="classNames">
    <input
      type="radio"
      :class="classes.input"
      :name="name"
      :value="value"
      :checked="isChecked"
      :disabled="disabled"
      @change="handleChange"
    />
    <span v-if="isCustomMode" :class="classes.control">
      <span :class="classes.icon">
        <slot v-if="isChecked" name="checkedIcon" />
        <slot v-else name="uncheckedIcon" />
      </span>
    </span>
    <span v-if="label || slots.default" :class="classes.label">
      <slot>{{ label }}</slot>
    </span>
  </label>
</template>

// src/react/components/Radio/Radio.tsx
import { forwardRef } from "react";

import { COMPONENT_NAMES, CSS_CLASSES } from "@/core/constants";
import type { TRadioProps } from "./Radio.types";

const classes = CSS_CLASSES.radio;

/**
 * Radio component for React
 *
 * Supports two modes:
 * - Native mode (default): Uses browser's native radio
 * - Custom mode: Uses custom icons when checkedIcon/uncheckedIcon are provided
 *
 * @example
 * ```tsx
 * // Native mode
 * <Radio name="option" value="a" label="Option A" />
 *
 * // Custom mode with icons
 * <Radio
 *   name="option"
 *   value="a"
 *   label="Option A"
 *   checkedIcon={<Icon icon="mdi:radiobox-marked" />}
 *   uncheckedIcon={<Icon icon="mdi:radiobox-blank" />}
 * />
 * ```
 */
export const Radio = forwardRef<HTMLInputElement, TRadioProps>(function Radio(
  { size = "md", checked, disabled = false, name, value, label, checkedIcon, uncheckedIcon, className = "", ...rest },
  ref,
) {
  const isCustomMode = Boolean(checkedIcon || uncheckedIcon);

  const classNames = [
    classes.root,
    classes.sizes[size],
    isCustomMode ? classes.custom : "",
    checked ? classes.states.checked : "",
    disabled ? classes.states.disabled : "",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <label className={classNames}>
      <input
        ref={ref}
        type="radio"
        className={classes.input}
        name={name}
        value={value}
        checked={checked}
        disabled={disabled}
        {...rest}
      />
      {isCustomMode && (
        <span className={classes.control}>
          <span className={classes.icon}>{checked ? checkedIcon : uncheckedIcon}</span>
        </span>
      )}
      {label && <span className={classes.label}>{label}</span>}
    </label>
  );
});

Radio.displayName = COMPONENT_NAMES.Radio;
