// src/vue/components/Switch/Switch.vue
<script setup lang="ts">
import { computed } from "vue";

import { CSS_CLASSES } from "@/core/constants";
import type { TSwitchProps } from "./Switch.types";

const classes = CSS_CLASSES.switch;

const props = withDefaults(defineProps<TSwitchProps>(), {
  size: "md",
  checked: undefined,
  disabled: false,
  className: "",
});

const emit = defineEmits<{
  "update:modelValue": [value: boolean];
  change: [value: boolean];
}>();

const isChecked = computed(() => props.modelValue ?? props.checked);

const classNames = computed(() => {
  return [
    classes.root,
    classes.sizes[props.size],
    isChecked.value ? classes.states.checked : "",
    props.disabled ? classes.states.disabled : "",
    props.className,
  ]
    .filter(Boolean)
    .join(" ");
});

function handleChange(event: Event) {
  const target = event.target as HTMLInputElement;
  emit("update:modelValue", target.checked);
  emit("change", target.checked);
}
</script>

<template>
  <label :class="classNames">
    <input type="checkbox" :checked="isChecked" :disabled="disabled" @change="handleChange" />
    <span :class="classes.track">
      <span :class="classes.thumb" />
    </span>
    <span v-if="label" :class="classes.label">{{ label }}</span>
  </label>
</template>

// src/react/components/Switch/Switch.tsx
import { forwardRef } from "react";

import { COMPONENT_NAMES, CSS_CLASSES } from "@/core/constants";
import type { TSwitchProps } from "./Switch.types";

const classes = CSS_CLASSES.switch;

/**
 * Switch component for React
 *
 * @example
 * ```tsx
 * <Switch checked={isOn} onChange={(e) => setIsOn(e.target.checked)} />
 * ```
 */
export const Switch = forwardRef<HTMLInputElement, TSwitchProps>(function Switch(
  { size = "md", checked, disabled = false, label, className = "", ...rest },
  ref,
) {
  // Support both controlled (checked prop) and uncontrolled (defaultChecked) modes
  const isControlled = checked !== undefined;

  const classNames = [
    classes.root,
    classes.sizes[size],
    checked ? classes.states.checked : "",
    disabled ? classes.states.disabled : "",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <label className={classNames}>
      <input ref={ref} type="checkbox" checked={isControlled ? checked : undefined} disabled={disabled} {...rest} />
      <span className={classes.track}>
        <span className={classes.thumb} />
      </span>
      {label && <span className={classes.label}>{label}</span>}
    </label>
  );
});

Switch.displayName = COMPONENT_NAMES.Switch;
