// src/vue/components/Button/Button.vue
<script setup lang="ts">
import { computed } from "vue";

import { CSS_CLASSES } from "@/core/constants";
import type { TButtonProps } from "./Button.types";

const classes = CSS_CLASSES.button;

const props = withDefaults(defineProps<TButtonProps>(), {
  size: "md",
  variant: "solid",
  colorScheme: "theme",
  disabled: false,
  fullWidth: false,
  className: "",
});

const classNames = computed(() => {
  return [
    classes.root,
    classes.sizes[props.size],
    classes.variants[props.variant],
    props.colorScheme !== "theme" ? classes.colors[props.colorScheme] : "",
    props.fullWidth ? classes.states.fullWidth : "",
    props.className,
  ]
    .filter(Boolean)
    .join(" ");
});
</script>

<template>
  <button :class="classNames" :disabled="disabled">
    <slot />
  </button>
</template>

// src/react/components/Button/Button.tsx
import { forwardRef } from "react";

import { COMPONENT_NAMES, CSS_CLASSES } from "@/core/constants";
import type { TButtonProps } from "./Button.types";

const classes = CSS_CLASSES.button;

/**
 * Button component for React
 */
export const Button = forwardRef<HTMLButtonElement, TButtonProps>(function Button(
  {
    size = "md",
    variant = "solid",
    colorScheme = "theme",
    disabled = false,
    fullWidth = false,
    className = "",
    children,
    ...rest
  },
  ref,
) {
  const classNames = [
    classes.root,
    classes.sizes[size],
    classes.variants[variant],
    colorScheme !== "theme" ? classes.colors[colorScheme] : "",
    fullWidth ? classes.states.fullWidth : "",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <button ref={ref} className={classNames} disabled={disabled} {...rest}>
      {children}
    </button>
  );
});

Button.displayName = COMPONENT_NAMES.Button;
