// src/vue/components/Skeleton/Skeleton.vue
<script setup lang="ts">
import { computed } from "vue";

import { CSS_CLASSES } from "@/core/constants";
import type { TSkeletonProps } from "./Skeleton.types";

const classes = CSS_CLASSES.skeleton;

const props = withDefaults(defineProps<TSkeletonProps>(), {
  variant: "rect",
  animation: "pulse",
  className: "",
});

const classNames = computed(() => {
  return [
    classes.root,
    props.variant !== "rect" ? classes.variants[props.variant] : "",
    props.animation ? classes.animations[props.animation] : "",
    props.className,
  ]
    .filter(Boolean)
    .join(" ");
});

const mergedStyle = computed(() => {
  const s: Record<string, string> = {};
  if (props.width !== undefined) s.width = typeof props.width === "number" ? `${props.width}px` : props.width;
  if (props.height !== undefined) s.height = typeof props.height === "number" ? `${props.height}px` : props.height;
  return s;
});
</script>

<template>
  <span :class="classNames" :style="mergedStyle" aria-hidden="true">
    <slot />
  </span>
</template>

// src/react/components/Skeleton/Skeleton.tsx
import { forwardRef, useMemo } from "react";

import { COMPONENT_NAMES, CSS_CLASSES } from "@/core/constants";
import type { TSkeletonProps } from "./Skeleton.types";

const classes = CSS_CLASSES.skeleton;

/**
 * Skeleton component for React
 *
 * A placeholder loading indicator with pulse or wave animation.
 * Use to show content layout while data is loading.
 */
export const Skeleton = forwardRef<HTMLSpanElement, TSkeletonProps>(function Skeleton(
  { variant = "rect", animation = "pulse", width, height, className = "", style, ...rest },
  ref,
) {
  const classNames = [
    classes.root,
    variant !== "rect" ? classes.variants[variant] : "",
    animation ? classes.animations[animation] : "",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  const mergedStyle = useMemo(() => {
    const s: React.CSSProperties = { ...style };
    if (width !== undefined) s.width = typeof width === "number" ? `${width}px` : width;
    if (height !== undefined) s.height = typeof height === "number" ? `${height}px` : height;
    return s;
  }, [width, height, style]);

  return <span ref={ref} className={classNames} style={mergedStyle} aria-hidden="true" {...rest} />;
});

Skeleton.displayName = COMPONENT_NAMES.Skeleton;
